### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by cabhara** [dlowder-salesforce/ReactNavigationTVDemo#2]
I used the demo as a starting point for a project, but no images would show (Apple TV 14.2). I upgraded the SDK to `"react-native": "npm:react-native-tvos@0.63.1-2"`, but now I'm getting a pod install error: ```
[!] CocoaPods could not find compatible versions for pod "ReactCommon/callinvoker":
  In snapshot (Podfile.lock):
    ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)

  In Podfile:
    ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)

None of your spec sources contain a spec satisfying the dependency: `ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Appreciate any advice.

Alternatively, I just tried adding react navigation to a working TVos project, but ran into issues getting react navigation to work, so I started with the demo code. (are there any instructions on how to add react navigation to an existing project)

Thanks!

**Comment by douglowder** [comment]
@cabhara I have two recommendations:

- Use the latest version of `react-native-tvos`, 0.63.1-4 (or just use `"react-native": "npm:react-native-tvos"`)
- Delete the `Podfile.lock` before executing `pod install`

**Comment by cabhara** [comment]
Thanks for your reply!

still getting a similar error:

Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "ReactCommon/callinvoker":
  In Podfile:
    ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)

None of your spec sources contain a spec satisfying the dependency: `ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

[!] Found multiple specifications for `FlipperKit (0.30.2)`:
- /Users/cbharara/.cocoapods/repos/react-native-community/FlipperKit/0.30.2/FlipperKit.podspec.json
- /Users/cbharara/.cocoapods/repos/master/Specs/3/2/5/FlipperKit/0.30.2/FlipperKit.podspec.json

**Comment by douglowder** [comment]
Ok I'll take a look, probably the Podfile is out of date

**Comment by douglowder** [comment]
@cabhara there were significant changes to the way the Podfile pulls in RN pods between 0.61.2 and 0.63.1, and other dependencies changed versions.  I've pushed the required changes to master -- the project now builds and runs from scratch for me on tvOS 14.2.  It uses `react-native-tvos@0.63.1-4`, which includes the fix for images on tvOS/iOS 14.
